id: A328911D4
title: Advice for Urgyen Tsomo
type: translation
pechas:
- I4F6447CC
- I2C9CCFF4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:13.217749
  last_modified_at: 2023-01-04 11:51:13.217761
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I4F6447CC/D0EB: 93B5
  I2C9CCFF4/AAD8: 93B5
